import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
    server: {
        DATABASE_URL: z.string().url(),
        CLERK_SECRET_KEY: z.string().min(1),
        CLERK_WEBHOOK_SECRET: z.string().min(1),
        REDIS_URL: z.string().url(),
        GEMINI_API_KEY: z.string().min(1),
        IMAGEKIT_PRIVATE_KEY: z.string().min(1),
        TOKEN_ENCRYPTION_KEY: z.string().min(64),
        META_APP_ID: z.string().min(1),
        META_APP_SECRET: z.string().min(1),
        TWITTER_CLIENT_ID: z.string().min(1),
        TWITTER_CLIENT_SECRET: z.string().min(1),
        LINKEDIN_CLIENT_ID: z.string().min(1),
        LINKEDIN_CLIENT_SECRET: z.string().min(1),
        TIKTOK_CLIENT_KEY: z.string().min(1),
        TIKTOK_CLIENT_SECRET: z.string().min(1),
        GOOGLE_CLIENT_ID: z.string().min(1),
        GOOGLE_CLIENT_SECRET: z.string().min(1),
        PINTEREST_APP_ID: z.string().min(1),
        PINTEREST_APP_SECRET: z.string().min(1),
        DISCORD_BOT_TOKEN: z.string().min(1),
        SLACK_CLIENT_ID: z.string().min(1),
        SLACK_CLIENT_SECRET: z.string().min(1),
        NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
    },
    client: {
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
        NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY: z.string().min(1),
        NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT: z.string().url(),
        NEXT_PUBLIC_APP_URL: z.string().url(),
    },
    runtimeEnv: {
        DATABASE_URL: process.env.DATABASE_URL,
        CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
        CLERK_WEBHOOK_SECRET: process.env.CLERK_WEBHOOK_SECRET,
        REDIS_URL: process.env.REDIS_URL,
        GEMINI_API_KEY: process.env.GEMINI_API_KEY,
        IMAGEKIT_PRIVATE_KEY: process.env.IMAGEKIT_PRIVATE_KEY,
        TOKEN_ENCRYPTION_KEY: process.env.TOKEN_ENCRYPTION_KEY,
        META_APP_ID: process.env.META_APP_ID,
        META_APP_SECRET: process.env.META_APP_SECRET,
        TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID,
        TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET,
        LINKEDIN_CLIENT_ID: process.env.LINKEDIN_CLIENT_ID,
        LINKEDIN_CLIENT_SECRET: process.env.LINKEDIN_CLIENT_SECRET,
        TIKTOK_CLIENT_KEY: process.env.TIKTOK_CLIENT_KEY,
        TIKTOK_CLIENT_SECRET: process.env.TIKTOK_CLIENT_SECRET,
        GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
        GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
        PINTEREST_APP_ID: process.env.PINTEREST_APP_ID,
        PINTEREST_APP_SECRET: process.env.PINTEREST_APP_SECRET,
        DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN,
        SLACK_CLIENT_ID: process.env.SLACK_CLIENT_ID,
        SLACK_CLIENT_SECRET: process.env.SLACK_CLIENT_SECRET,
        NODE_ENV: process.env.NODE_ENV,
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
        NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY: process.env.NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY,
        NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT: process.env.NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT,
        NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    },
});
